### ISSUE TITLE
Error : ibm-blockchain-js 'length' of undefinde

### ISSUE THREAD

**Issue by bd37** [IBM-Blockchain/cp-web#21]
When I run node app.js, I receive the following error. How can I fix about this?

/cp-web/node_modules/ibm-blockchain-js/index.js:780
                if(ibc.chaincode.details.deployed_name.length < 32) ibc.chaincode.details.deployed_name = '';                   //doesnt look right, let code below catch error

**Comment by masterDev1985** [comment]
@bd37 is this your first time running the application?  If not, have you made any modifications to the demo?  Finally, are you sure that this is the first error that you see?  I'm wondering if a chaincode deployment failed at some point before this error.

**Comment by dshuffma-ibm** [comment]
This code only runs when the peer returned a response that is out of spec.  Something bad has happened to this peer, and it is likely out of your hands to fix it. Your best bet is to delete the network and get a new one.

I suppose a second potential issue could be if your deploy parameters are not correct, but I would then expect the response to have a correctly formatted error. Might be worth double checking the deploy  parameter anyway: `chaincode.git_url`.  Should look like `https://github.com/IBM-Blockchain/cp-chaincode-v2/hyperledger` but instead of "IBM-Blockchain" it might be your username if you are using a forked version.

**Comment by masterDev1985** [comment]
@bd37 Any further questions or concerns?

**Comment by bd37** [comment]
Thanks, masterDev
