### ISSUE TITLE
How to change start user value($10,000,000,00) and currency?

### ISSUE THREAD

**Issue by pavelpasha** [IBM-Blockchain/cp-web#23]

**Comment by mastersingh24** [comment]
@pavelpasha  - you'll need to modify the chaincode associated with the project in order to change the initial start value.  The line to change is https://github.com/IBM-Blockchain/cp-chaincode-v2/blob/master/hyperledger/cp_cc.go#L143

The chaincode itself is not "currency" aware at this point so you can likely just just this in the formatting of the values in cp-web

**Comment by masterDev1985** [comment]
@mastersingh24 is correct.  I'll close the issue.
