### ISSUE TITLE
gRPC ECAA:checkRegistrarSignature: no registrar was specified

### ISSUE THREAD

**Issue by kamraanki** [IBM-Blockchain/cp-web#27]
I have deployed commercial paper demo on IBM bluemix. While registration new user to membership services i got following error:-

OUT - TRACE: 2016/07/21 04:13:45 eca.go:477: gRPC ECAA:checkRegistrarSignature: no registrar was specified

**Comment by masterDev1985** [comment]
We are currently experiencing an outage on Bluemix.  However, this could be cause by the connector which is being used by the cp demo to no longer be compatible with the v0.5 developer preview release of the fabric, which is now in the Bluemix service.  Let's try this again once everything is working again.

**Comment by masterDev1985** [comment]
@kamraanki Since my last message, we've restored the Bluemix service and have pushed a large update to the CP demo.  User registration is now performed through the fabric SDK instead of the loopback-connector library.  I suspect you'll be able to resolved the error you are seeing after looking at the newer user registration code.
