### ISSUE TITLE
Failed loading TCertOwnerKDFKey. Key is missing.

### ISSUE THREAD

**Issue by kamraanki** [IBM-Blockchain/cp-web#32]
Hi i have setup fabric network on my local when i deploy cp-web on this network it gives following errors:-

grpc: Server.Serve failed to complete security handshake

Failed loading TCertOwnerKDFKey. Key is missing.

23:37:02.064 [chaincode] Launch -> ERRO 16d launchAndWaitForRegister failed Timeout expired while starting chaincode bc25e42864477feeeedbfb5fecb7fea0c5bba627f9af2acf9c19746f705e671019dd04c1f7f7282f62a7cbefba1780d78b27507e777b3620713d7df37131442f(networkid:dev,peerid:vp0,tx:bc25e42864477feeeedbfb5fecb7fea0c5bba627f9af2acf9c19746f705e671019dd04c1f7f7282f62a7cbefba1780d78b27507e777b3620713d7df37131442f)

**Comment by masterDev1985** [comment]
https://github.com/hyperledger/fabric/blob/f483fad3332968866a3067618c85a81561bb4ea3/core/crypto/client_tca.go#L81

https://github.com/hyperledger/fabric/blob/2cd1383ea135f813718dcbbf47c3908a1e74d3d7/core/crypto/node_ks.go#L111

According to the code above, this error is generated by a missing file path for a key.  These logs also look like they came from different places.  Do you have any logs from the chaincode container that the peer attempted to create?

**Comment by kamraanki** [comment]
@masterDev1985  Please find logs of peer below:-

![image](https://cloud.githubusercontent.com/assets/19260567/17174005/d8b9d112-541b-11e6-82cd-b88d5ec3e1e2.png)

**Comment by masterDev1985** [comment]
We saw similar errors in the early days of standing up networks for use in the Bluemix service.  Obviously, the certificates you are generating have some problematic validity periods.  For us, the issue was that differences between the clocks on all of the peers would cause our certificates to appear to not be valid yet on some of the peers.  The fix that we eventually settled on was to generate the certificates as being valid from a few minutes in the past, to account for this clock drifting.
