### ISSUE TITLE
error in query post - ibm bluemix

### ISSUE THREAD

**Issue by sriefx143** [IBM-Blockchain/cp-web#43]
My invoke call works fine, however while trying to query i am getting following error:

```
"data": "Error when querying chaincode: Error:Failed to launch chaincode spec(premature execution - chaincode (abe2a....1) is being launched)"
```

is there any fix?

**Comment by dhyey20** [comment]
- The chaincode is still being deployed and I would recommend waiting for couple of more minutes before querying the chaincode. You can call `chain.setDeployWaitTime(x)` setting x to a higher value so that the chaincode is deployed successfully before you start querying.
- It all depends on the load, but in the past I have seen it take 6-7 minutes to deploy the chaincode.

**Comment by sriefx143** [comment]
Well, i dont think that is what is happening here since I am able to execute the chaincode by calling "invoke" method.
I have done 5 invoke calls, all of which executed fine and 
I got transaction UUID back.
I am getting this error only while reading.

**Comment by mariwade** [comment]
I have been having the same experience for several days.  I deployed and invoked the chain code.  I can see the blocks and their payload through the Bluemix, Blockchain tab.  I can not query it either.  After reading this I tried several hrs later and query results in:

{
   "jsonrpc": "2.0",
   "error": {
     "code": -32003,
     "message": "Query failure",
     "data": "Error when querying chaincode: Error:Failed to launch chaincode spec(Error starting container: API error (500): Error: image library/2dbde5fc-eaec-4382-b036-9dc2d5f343b1-vp1-bc1b00b2b4827e5454d55e423940e2728dcd591c3767013ce28e71819e463728df5e0a665fb62a898085e870b0d0970ecc522ccd4bf9d1b1f0f5525efdca486a not found\n)"
   },
   "id": 0
 }

**Comment by masterDev1985** [comment]
Deployments and invokes take a long time to complete after you submit them.  So, when you get a transaction ID back for these requests, that doesn't mean that the transaction was actually completed; it just means that it was submitted.  The way to debug this properly would be to attempt to deploy chaincode, wait a minute, and then search your peer logs for messages with the tags `docker`, `container`, `chaincode`, or `vm`.  There should be a log that shows some sort of deployment error.

**Comment by sriefx143** [comment]
Thank you. yes, got through the logs and found this error message:

ERR - [36m13:43:58.525 [chaincode] processStream -> DEBU e7aa6[0m Got error: [9ec6afeb... Chaincode handler FSM cannot handle message (ERROR) with payload size (164) while in state: ready
ERR - [36m13:43:58.525 [chaincode] HandleMessage -> DEBU e7aa7[0m [9ec6afeb]Handling ChaincodeMessage of type: ERROR in state transaction

how do I track this error back to the source? appreciate your help

**Comment by masterDev1985** [comment]
The deployment flow in the peer logs is typically this:
1. Messages about the deployment request being received.
2. Lots of messages about consensus on the transaction.
3. `docker` and `container` logs related to creating a container to run the deployed chaincode.

You want to track down the messages in this third group.  However, because the peer logs are so verbose, old logs tend to fall off the back of the log rotation pretty quickly.  It might take a few tries to get a feel for catching these messages.

**Comment by sriefx143** [comment]
redeployed and it works fine.  Thanks for the notes - was able to track through the logs to check whats happened.
